import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

/**
 * POST /api/notify/email
 * Body: { to, subject?, message, isAiGenerated?: boolean }
 * Sends a verification email to the user indicating whether the response
 * they received was generated by AI or not, along with the message content.
 */
export async function POST(request) {
  try {
    const body = await request.json();
    const { to, subject, message, isAiGenerated } = body || {};

    if (!to || !message) {
      return NextResponse.json({ success: false, error: 'Missing required fields: to, message' }, { status: 400 });
    }

    // Configure transporter via environment variables
    const host = process.env.EMAIL_HOST;
    const port = Number(process.env.EMAIL_PORT || 587);
    const user = process.env.EMAIL_USER;
    const pass = process.env.EMAIL_PASS;
    const from = process.env.EMAIL_FROM || `KnowledgeHub <${user || 'no-reply@localhost'}>`;

    let transporter;
    let usingTest = false;
    if (!host || !user || !pass) {
      // Fallback to Ethereal test account so developers can preview emails without real SMTP
      const testAccount = await nodemailer.createTestAccount();
      transporter = nodemailer.createTransport({
        host: 'smtp.ethereal.email',
        port: 587,
        secure: false,
        auth: {
          user: testAccount.user,
          pass: testAccount.pass,
        },
      });
      usingTest = true;
    } else {
      transporter = nodemailer.createTransport({
        host,
        port,
        secure: port === 465, // true for 465, false for other ports
        auth: { user, pass },
      });
    }

    const aiBadge = isAiGenerated === true
      ? '✅ This response was generated by AI.'
      : (isAiGenerated === false ? 'ℹ️ This response was not generated by AI.' : '');

    const html = `
      <div style="font-family:Inter,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;max-width:600px;margin:auto;padding:24px;background:#f8fafc;color:#0f172a">
        <h2 style="margin:0 0 12px;font-size:20px;color:#111827">KnowledgeHub Notification</h2>
        ${aiBadge ? `<p style="margin:0 0 12px;font-size:14px;color:#374151">${aiBadge}</p>` : ''}
        <div style="background:#ffffff;border:1px solid #e5e7eb;border-radius:12px;padding:16px">
          <p style="white-space:pre-wrap;margin:0;font-size:14px;color:#111827">${escapeHtml(message)}</p>
        </div>
        <p style="margin-top:16px;font-size:12px;color:#6b7280">If you have questions, reply to this email.</p>
      </div>
    `;

    const info = await transporter.sendMail({
      from,
      to,
      subject: subject || (isAiGenerated ? 'KnowledgeHub • AI Response Verification' : 'KnowledgeHub • Response Notification'),
      html,
    });

    const previewUrl = usingTest ? nodemailer.getTestMessageUrl(info) : null;
    return NextResponse.json({ success: true, messageId: info.messageId, previewUrl });
  } catch (err) {
    console.error('POST /api/notify/email', err);
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }
}

function escapeHtml(str = '') {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
